// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QtHhi7Q8x5D7Z7XdvcbUJL-NibLWSnQ',
    appId: '1:599901055825:web:a3bb411c313c9397044170',
    messagingSenderId: '599901055825',
    projectId: 'foodni-project',
    authDomain: 'foodni-project.firebaseapp.com',
    storageBucket: 'foodni-project.firebasestorage.app',
    measurementId: 'G-RCYLVBV4L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItn03No4KghKwkfUuScFeVpcm8YkSDBc',
    appId: '1:599901055825:android:101f7aea155bd135044170',
    messagingSenderId: '599901055825',
    projectId: 'foodni-project',
    storageBucket: 'foodni-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9oGv763NZ3raOVHf3yZKmHfpFd06dSo',
    appId: '1:599901055825:ios:dd3b9b8660483fe4044170',
    messagingSenderId: '599901055825',
    projectId: 'foodni-project',
    storageBucket: 'foodni-project.firebasestorage.app',
    iosClientId: '599901055825-d2gqdrjku9ihgk2jto80na0f6n4sv0hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodNi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9oGv763NZ3raOVHf3yZKmHfpFd06dSo',
    appId: '1:599901055825:ios:dd3b9b8660483fe4044170',
    messagingSenderId: '599901055825',
    projectId: 'foodni-project',
    storageBucket: 'foodni-project.firebasestorage.app',
    iosClientId: '599901055825-d2gqdrjku9ihgk2jto80na0f6n4sv0hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodNi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QtHhi7Q8x5D7Z7XdvcbUJL-NibLWSnQ',
    appId: '1:599901055825:web:bcdbc84bad64ee5e044170',
    messagingSenderId: '599901055825',
    projectId: 'foodni-project',
    authDomain: 'foodni-project.firebaseapp.com',
    storageBucket: 'foodni-project.firebasestorage.app',
    measurementId: 'G-CYQRBGDMVG',
  );
}
